version: '3'

services:
  frontend:
    build:
      context: frontend
    tty: true
    command: sh -c "cd /frontend/insta && npm run dev"
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true

  backend:
    build:
      context: backend
    tty: true
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
